server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    #SpringCloudGateway路由配置方式
    gateway:
      #是否与服务发现组件进行结合，通过serviceId（必须设置成大写）转发到具体的服务实例
      #默认为false，设置为true便开启通过服务中心的自动根据serviceId创建路由的功能
      #路由访问方式： http://Gateway_HOST:Gateway_PORT/大写的serviceId/**
      discovery:
        locator:
          enabled: true
          #服务serviceId不分区大小写
          lowerCaseServiceId: true
      routes:
        #网关路由的转发 lb:// 表示是从注册中心发现serviceId
        - id: demo-client
          uri: lb://demo-client
          predicates:
            - Path=/demo-client/**
          filters:
            - StripPrefix=1
        - id: blog-client
          uri: lb://blog-client
          predicates:
            - Path=/blog-client/**
          filters:
            - StripPrefix=1
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8100/eureka/
logging:
  #配置网关日志策略
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug